name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nbclick_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env.test to .env
        run: cp nbclick_app/.env.test nbclick_app/.env

      - name: Verify repo structure
        run: ls -la

      - name: Move to project directory
        run: cd nbclick_app && ls -la

      - name: Install dependencies
        run: cd nbclick_app && composer install --no-progress --prefer-dist --optimize-autoloader && composer require --dev doctrine/doctrine-fixtures-bundle
  
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h127.0.0.1 --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Verify MySQL connection
        run: |
          mysql --host=127.0.0.1 --port=3306 -uroot -proot -e "SHOW DATABASES;"

      - name: Set up database
        run: |
          cd nbclick_app
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --force --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction
      
      - name: Verify fixture data
        run: |
          cd nbclick_app
          php bin/console doctrine:query:sql "SELECT * FROM user" --env=test

      - name: Run tests
        run: cd nbclick_app && php bin/phpunit
