name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nbclick_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify repo structure
        run: ls -la

      - name: Move to project directory
        run: cd nbclick_app && ls -la  

      - name: Install dependencies
        run: cd nbclick_app && composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set up database
        run: |
            cd nbclick_app
            php bin/console doctrine:database:create --env=test
            php bin/console doctrine:schema:update --force --env=test

      - name: Run tests
        run: cd nbclick_app && php bin/phpunit
